name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:

          #heroku_api_key: ${{secrets.2e01561c-9bd6-4e50-9be2-c6c837e2b0c2}}
          heroku_api_key: 5848382d-c972-4aa8-ba90-da74733b1235
          heroku_app_name: "proj-2" #Must be unique in Heroku
          heroku_email: "nlaramee120@aol.com"
          usedocker: false
